name: NMLOverhealthSystem
version: '1.0'
main: io.github.NoOne.nMLOverhealthSystem.NMLOverhealthSystem
api-version: '1.21'
depend:
  - NMLPlayerStats
commands:
  setMaxOverhealth:
    description: Sets the user's max overhealth
    usage: /<command>